channels:
- defaults
- pytorch
dependencies:
- python=3.6.9
- pip:
  - pip==19.3.1
  - mlflow==1.8.0
  - cloudpickle==1.3.0
  - torch==1.5.0
  #- transformers;;; For training, transformers must be installed from source
name: mlflow-env-bert
